# Generated by Django 3.0.3 on 2020-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=12), max_digits=12),
        ),
    ]
