# Generated by Django 3.0.3 on 2020-03-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer_app', '0004_auto_20200325_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontype',
            old_name='type',
            new_name='type_name',
        ),
    ]
