# Generated by Django 3.0.3 on 2020-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer_app', '0006_auto_20200330_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
