# Generated by Django 3.0.3 on 2020-11-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer_app', '0007_transactioncategory_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeteer_app.TransactionCategory')),
            ],
        ),
    ]
