# Generated by Django 3.0.3 on 2020-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteer_app', '0008_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('semi-monthly', 'Semi-monthly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annually', 'Semi-annually'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
    ]
